[package]
name = "webrtc"
version = "0.1.0"
authors = ["Ryo Abe <rabe.scor.esys@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7.2"
failure = "0.1.5"
num = "*"
webrtc-sdp = "0.3.1"
serde_json = "*"